version: '3.3'

services:
  web:
    image: levart
    environment:
      EMAIL_HOST:  # Email Host
      EMAIL_USERNAME:  # Email Username
      EMAIL_PASSWORD:  #Email Password
      JWT_SECRET: 'supersecret'
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:12-bullseye
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: