version: '3.3'

services:
  web:
    image: levart
    environment:
      EMAIL_HOST: 'live.smtp.mailtrap.io'
      EMAIL_USERNAME: 'api'
      EMAIL_PASSWORD: '7816f9a70d5e42e839c23ce4f9a8bdc3'
      JWT_SECRET: 'supersecret'
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:12-bullseye
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: